`aws-keychain migrate` login.keychain to aws-keychain.keychain

diff --git a/aws-keychain b/aws-keychain
--- a/aws-keychain
+++ b/aws-keychain
@@ -24,6 +24,7 @@ main() {
     add) aws_keychain_add "$@" ;;
     exec) aws_keychain_exec "$@" ;;
     ls) aws_keychain_ls "$@" ;;
+    migrate) aws_keychain_migrate "$@" ;;
     rm) aws_keychain_rm "$@" ;;
     *) aws_keychain_usage ;;
   esac
@@ -62,6 +63,7 @@ aws_keychain_exec() {
   if [ -z "$id" -o -z "$secret" ]; then
     echo >&2 "No credentials for '$name':"
     echo >&2 "$raw"
+    echo >&2 "You may need to 'aws-keychain migrate'"
     exit 1
   fi
   AWS_ACCESS_KEY_ID="$id" AWS_SECRET_ACCESS_KEY="$secret" "$@"
@@ -91,6 +93,21 @@ aws_keychain_extract_password() {
 aws_keychain_ls() {
   [ $# -eq 1 ] || aws_keychain_usage "aws-keychain ls"
   cat $AWS_CREDENTIALS_LIST | sort | uniq
+}
+
+aws_keychain_migrate() {
+  local src=${AWS_KEYCHAIN_FILE_SRC:-"$HOME/Library/Keychains/login.keychain"}
+  local dst="$AWS_KEYCHAIN_FILE"
+  local tmp_list="$AWS_CREDENTIALS_LIST-migrate"
+  cp -- "$AWS_CREDENTIALS_LIST" "$tmp_list"
+  for name in $(aws_keychain_ls ls); do
+    if [ "$src" = "$dst" ]; then echo >&2 "Cannot migrate from $src to $dst"; exit 1; fi
+    echo "Migrating $name from '$src' to '$dst'"
+    AWS_KEYCHAIN_FILE="$src" aws-keychain exec $name \
+      bash -c "AWS_KEYCHAIN_FILE="$dst" $0 add \"$name\" \"\$AWS_ACCESS_KEY_ID\" \"\$AWS_SECRET_ACCESS_KEY\""
+    AWS_KEYCHAIN_FILE="$src" AWS_CREDENTIALS_LIST="$tmp_list" $0 rm $name
+  done
+  rm -- "$tmp_list"
 }
 
 aws_keychain_rm() {
